# first the parameter section. This section will be used when creating the resource . We need to specify the type for the parameters.
# Parameters are input data. we would need to provide inputs values for these parameters. Cloudformation will provide space to provide inputs. 

Parameters:
  NameOfService:
    Description: "The name of the service this stack is to be used for."
    Type: String
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access into the server
    Type: AWS::EC2::KeyPair::KeyName

# this is the mapping section. Depending on the mapping the resources will be selected
Mappings:
  RegionMap:
    ap-southeast-2:
      AMI: ami-0d6857b844e855670
# this is the main section that creates the resources.   
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    # metadata is used by the 
    Properties:
      InstanceType: t2.micro
      ImageId:
        Fn::FindInMap:
        - RegionMap
        - !Ref AWS::Region
        - AMI
      SecurityGroupIds:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: !Ref NameOfService
      KeyName: !Ref KeyName
      
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open Ports 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      
