# this is a simple E22 instance template that spins a EC2 instance with a Security group

Resources:
  LinuxEC2:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.micro
      ImageId: ami-43874721 # Amazon Linux AMI in Sydney
      SecurityGroups: 
        - !Ref SGEnableSSH
      Tags:
        - Key: "Name"
          Value: !Join #incintic function to join the name with the parameter 
            - ""
            - - "EC2 Instance for "
              - !Ref AWS::Region

  # security group
  SGEnableSSH:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0